# Import NumPy

In [1]:
import numpy as np

# 1. Create a 5 element array using your favorite numbers named 'myFavorites'

In [2]:
myFavorites = np.array([13,27,8,2,4])

# 2. Perform each of the 5 aggregate functions on your array

In [3]:
myFavorites.min()

2

In [4]:
myFavorites.max()

27

In [5]:
myFavorites.sum()

54

In [6]:
myFavorites.mean()

10.8

In [7]:
myFavorites.std()

8.930845424706442

# 3. Create a 5 element array containing only ones named 'oneArrayToRuleThemAll'

In [8]:
oneArrayToRuleThemAll = np.ones(5)

In [9]:
oneArrayToRuleThemAll

array([1., 1., 1., 1., 1.])

# 4. Add 'myFavorites' and 'oneArrayToRuleThemAll'

In [10]:
myFavorites + oneArrayToRuleThemAll

array([14., 28.,  9.,  3.,  5.])

# 5. Multiply every element in 'myFavorites' by 2

In [11]:
myFavorites * 2

array([26, 54, 16,  4,  8])

# 6. Call the third element in 'myFavorites' using indexing

In [14]:
myFavorites

array([13, 27,  8,  2,  4])

In [15]:
myFavorites[2]

8

# 7. Create a 4 element, 2x2 matrix of numbers named 'theMatrixHasYou'

In [16]:
theMatrixHasYou = np.array([[3,4],[6,7]])

In [17]:
theMatrixHasYou

array([[3, 4],
       [6, 7]])

# 8. Access the upper left element in 'theMatrixHasYou' using indexing

In [18]:
theMatrixHasYou[0,0]

3

# 9. Find the largest number in each row for 'theMatrixHasYou'

In [19]:
theMatrixHasYou.max(axis=1)

array([4, 7])

# 10. Reshape 'theMatrixHasYou' into a matrix with 1 row and 4 columns

In [20]:
theMatrixHasYou.reshape(1,4)

array([[3, 4, 6, 7]])